import "dotenv/config";
import fs from "node:fs/promises";
import path from "node:path";
import Stripe from "stripe";
import { getAllProducts } from "../lib/datasource.impl";

const key = process.env.STRIPE_SECRET_KEY;
if (!key) throw new Error("STRIPE_SECRET_KEY is not set");
const stripe = new Stripe(key, { apiVersion: "2025-09-30.clover" });

const toKey = (pid: string, vid: string) => `${pid}:${vid}`;

async function findOrCreateProduct(p: { id: string; title: string }) {
  const q = `active:'true' AND metadata['canonical_product_id']:'${p.id}'`;
  const found = await stripe.products.search({ query: q, limit: 1 }).catch(() => ({ data: [] as Stripe.Product[] }));
  if (found.data[0]) return found.data[0];
  return stripe.products.create({ name: p.title, metadata: { canonical_product_id: p.id } });
}

async function findOrCreatePrice(args: {
  productKey: string;
  stripeProductId: string;
  currency: string;
  amount: number; // cents
  variantId: string;
}) {
  const { productKey, stripeProductId, currency, amount, variantId } = args;
  const q = [
    `active:'true'`,
    `product:'${stripeProductId}'`,
    `currency:'${currency.toLowerCase()}'`,
    `unit_amount:'${amount}'`,
    `metadata['canonical_key']:'${productKey}'`,
  ].join(" AND ");
  const found = await stripe.prices.search({ query: q, limit: 1 }).catch(() => ({ data: [] as Stripe.Price[] }));
  if (found.data[0]) return found.data[0];

  return stripe.prices.create({
    product: stripeProductId,
    currency: currency.toLowerCase(),
    unit_amount: amount,
    nickname: variantId,
    metadata: { canonical_key: productKey },
  });
}

async function main() {
  const catalog = await getAllProducts();
  const mapEntries: Array<[string, string]> = [];

  for (const p of catalog) {
    const sp = await findOrCreateProduct({ id: p.id, title: p.title });
    for (const v of p.variants) {
      const key = toKey(p.id, v.id);
      const unitAmount = Math.round((v.price ?? p.price) * 100);
      const price = await findOrCreatePrice({
        productKey: key,
        stripeProductId: sp.id,
        currency: p.currency ?? "usd",
        amount: unitAmount,
        variantId: v.id,
      });
      mapEntries.push([key, price.id]);
    }
  }

  // Write lib/pricing/priceMap.ts
  const outPath = path.join(process.cwd(), "lib/pricing/priceMap.ts");
  const lines = [
    `/** Auto-generated by scripts/stripe-sync.ts - DO NOT EDIT BY HAND */`,
    `export type CanonicalKey = \`\${string}:\${string}\`;`,
    `export const PRICE_MAP: Record<CanonicalKey, string> = {`,
    ...mapEntries.map(([k, v]) => `  "${k}": "${v}",`),
    `};`,
    `export function toKey(productId: string, variantId: string): CanonicalKey {`,
    `  return \`\${productId}:\${variantId}\`;`,
    `}`,
    `export function findPriceId(productId: string, variantId: string): string | null {`,
    `  const key = toKey(productId, variantId);`,
    `  return PRICE_MAP[key] ?? null;`,
    `}`,
    ``,
  ].join("\n");
  await fs.writeFile(outPath, lines, "utf8");

  // Also print for visibility
  console.log(`Updated ${outPath} with ${mapEntries.length} entries`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
